<?php
/**
 * Krish Technolabs
 * 
 * @package    Krish_LookBook
 * @copyright  Copyright (c) 2017 Krish Technolabs. (http://www.krishtechnolabs.com)
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>	
<?php echo $this->getChildHtml('influencergtm'); ?>
<?php

	/**
	*
	*
	* @var $this Scommerce_GoogleTagManagerPro_Block_List
	*/
	$_productCollection = $this->getProductCollection();
	$helper = Mage::helper('scommerce_googletagmanagerpro');
	$_influencer = Mage::registry('influencergtm');
	if (!$helper->isEnabled() || !$helper->isEEEnabled() || count($_productCollection)==0) return;

	$_category = Mage::getModel('catalog/layer')->getCurrentCategory();
	$_categoryName = '';
	if ($_category)
	{
		$store_id = Mage::app()->getStore()->getStoreId();
	    $_categoryName = $_category->getName();
	    $_categoryURL = $_category->getData('request_path');
	    $_categoryURLKey = $_category->getData('url_key');
	}

	$_mode = $this->getMode();
	$_productUrls = array();
	$_products = array();

	if ($_mode == 'category')
	{
 		$_impressionList = 'PLP_influencer_'. $_categoryURLKey.'/my-picks';	    
 		$_clickLabel   = $_impressionList;//'Category';
	}
	elseif ($_mode == 'search')
	{
	    $_impressionList = 'Search Results';
	    $_clickLabel   = $_impressionList;//'Results';
	}

	$_loop = 1;

	foreach ($_productCollection as $_product)
	{

	    $_productUrls[] = $_product->getProductUrl();
	    $_products[] = array(
	        'id' => $this->jsQuoteEscape($_product->getSku()),
	        'name'  => $this->jsQuoteEscape($_product->getName()),
			'price'  => $this->helper('core')->currency($_product->getPrice(),false,false),
	        'category' => $this->jsQuoteEscape($_categoryName),
	        'brand' => $this->jsQuoteEscape($helper->getBrand($_product)),
	        'list'  => $_impressionList,
	        'position' => $_loop,
	        'creative' => 'tile',
	        'dimension5' => $this->jsQuoteEscape(Mage::getModel('eav/entity_attribute_set')->load($_product->getAttributeSetId())->getAttributeSetName()),
			'dimension8' => $this->jsQuoteEscape($_product->getAttributeText('size')),
			'dimension10' => $this->jsQuoteEscape($_product->getSkinType()),
			'dimension12' => $this->jsQuoteEscape($_product->getSkinConcern()),
			'dimension14' => $this->jsQuoteEscape($_product->getResource()->getAttribute('fragrancetype')->getFrontend()->getValue($_product)),
			'dimension16' => $this->jsQuoteEscape($_product->getAttributeText('fragrance_notes'))
	    );

	    $_loop++;
	}

	$_JsProducts = json_encode($_products);
	$_JsProductUrls = json_encode($_productUrls);
	$results = array('products' =>$_JsProducts , 'prourls' =>$_JsProductUrls );
	?>

<script type='text/javascript'>
	    //<![CDATA[
      var jsProducts = jsProducts || [];
	    var jsProducts = jsProducts.concat(<?php echo $_JsProducts ?>);
		<?php $cookie = Mage::getSingleton('core/cookie');?>
		jQuery.removeCookie("productlist", { path: '/', domain: '<?php echo '.' . $cookie->getDomain()?>'});

		window.dataLayer = window.dataLayer || [];
    window.currencyCode = '<?php echo Mage::app()->getStore()->getCurrentCurrencyCode();?>';
    window.impressions = window.impressions || [];
    <?php foreach ($_products as $_product): ?>
        window.impressions.push({
             'name': '<?php echo $_product['name']?>',
             'id': '<?php echo $_product['id']?>',
             'price': '<?php echo $_product['price']?>',
             'brand': '<?php echo $_product['brand']?>',
             'category': '<?php echo $_product['category']?>',
             'list': '<?php echo $_product['list']?>',
             'position': '<?php echo $_product['position']?>',
             'creative': '<?php echo $_product['creative']?>',
             'dimension5': '<?php echo $_product['dimension5']?>',
             'dimension8': '<?php echo $_product['dimension8']?>',
             'dimension10': '<?php echo $_product['dimension10']?>',
             'dimension12': '<?php echo $_product['dimension12']?>',
             'dimension14': '<?php echo $_product['dimension14']?>',
             'dimension16': '<?php echo $_product['dimension16']?>',
        });
    <?php endforeach; ?>
</script>
<script type='text/javascript'>
	    //<![CDATA[
		var jsProductUrls = <?php echo $_JsProductUrls ?>;
	    var jsClickLabel = '<?php echo $_clickLabel?>';
	    jQuery('a').on('click', function(e){
	        var product;
	        var href = jQuery(this).attr('href');
	        var index = jsProductUrls.indexOf(href);

	        if (index != -1){
	            //event.preventDefault();
	            product = jsProducts[index];
				jQuery.cookie('productlist', product.list, { path: '/', domain: '<?php echo $helper->getCookieDomain()?>'});
				dataLayer.push({
					'event': 'productClick',
					'ecommerce': {
					  'click': {
						'actionField': {'list': '<?php echo $_clickLabel?>'}, 
						'products': [{
						  'name': product.name,   / Name or ID is required.
						  'id': product.id,
						  'price': product.price,
						  'brand': product.brand,
						  'category': product.category,
						  'position': product.position,
						  'dimension5': product.dimension5
						 }]
					   }
					 },
					 'eventCallback': function() {
					   if (!(e.ctrlKey || e.which==2)){
							document.location = href;
						}
					 }
				});
	        }
	    });
	    //]]>
</script>
